name: Feature request
description: Suggest a new feature or improvement
title: "Feature: "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        Describe the problem here..
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: |
        Describe a possible solution here..
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How big is this change?
      options:
        - Small change
        - Medium change
        - Large change
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Documents or extra information that may help explain the idea.
      placeholder: Screenshots, diagrams, or related issues
